version: "3.8"

services:
  frontend:
    build: ./frontend
    expose:
      - "80"
    restart: always
    networks:
      - web

  backend:
    build: ./server
    expose:
      - "4000"
    restart: always
    networks:
      - web

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email mail@fr4nc4.de --agree-tos --no-eff-email -d aiorfact.fun -d www.aiorfact.fun

networks:
  web:
