export const categoryMap = {
    "Glaube u. Religion 🙏": "glaube_religion",
    "Gaming 🎮": "gaming",
    "Essen u. Trinken 🍽️": "essen_trinken",
    "Gewässer 🌊": "gewaesser",
    "Labor 🧪": "labor",
    "Weltraum 🚀": "weltraum",
    "Länder 🌍": "laender",
    "Sport 🥇": "sport",
    "Philosophie 🌀": "philosophie",
    "Tiere 🐾": "tiere",
    "Musik 🎶": "musik",
    "Filme 🍿": "filme",
    "Geschichte 🏛️": "geschichte",
    "Technik 🛠️": "technik",
    "Bücher 📚": "buecher",
    "Biologie 🧬": "biologie",
    "Logik 🧠": "logik",
    "Hollywood 🎥": "hollywood",
    "Zufall 🎲": "zufall",
};